services:
  centos-ansible:
    hostname: centos-ansible
    build:
        context: ./centos/
        dockerfile: ./centos-Dockerfile
    ports:
      - 22002:22
      - 8280:80
    networks:
      - ansible-network
    volumes:
      - ./centos/playbooks/:/home/ansible/playbooks
    command: ["sh","-c","/entrypoint.sh"]
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512m

  debian-ansible:
    hostname: debian-ansible
    build:
        context: ./debian/
        dockerfile: ./debian-Dockerfile
    ports:
      - 8281:80
    networks:
      - ansible-network
    command: ["sh","-c","/entrypoint.sh"]
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512m

  archlinux-ansible:
    hostname: archlinux-ansible
    build:
        context: ./archlinux/
        dockerfile: ./archlinux-Dockerfile
    ports:
      - 8282:80
    networks:
      - ansible-network
    command: ["sh","-c","/entrypoint.sh"]
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512m

networks:
  ansible-network:
    external: false
    ipam:
      config:
        - subnet: 10.0.198.0/27
