services:
  centos-ansible:
    hostname: centos-ansible
    build:
        context: ./centos/
        dockerfile: ./centos-Dockerfile
    ports:
      - 22002:22
      - 8280:8080
    networks:
      - ansible-network
      - webapps-network
    volumes:
      - ./centos/playbooks/:/home/ansible/playbooks
      - ./centos/nginx.conf:/etc/nginx/nginx.conf
    command: ["sh","-c","/entrypoint.sh"]
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  debian-ansible:
    hostname: debian-ansible
    build:
        context: ./debian/
        dockerfile: ./debian-Dockerfile
    networks:
      - webapps-network
    command: ["sh","-c","/entrypoint.sh"]
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 512M

  archlinux-ansible:
    hostname: archlinux-ansible
    build:
        context: ./archlinux/
        dockerfile: ./archlinux-Dockerfile
    networks:
      - webapps-network
    command: ["sh","-c","/entrypoint.sh"]
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 512M

networks:
  webapps-network:
    external: false
    attachable: false
    # internal: true
    ipam:
      config:
        - subnet: 10.0.198.32/27

  ansible-network:
    external: false
    ipam:
      config:
        - subnet: 10.0.198.0/27
