#!/bin/bash
case "$1" in
  start)
    echo "Starting SSHD..."
    /usr/sbin/sshd
    ;;
  stop)
    echo "Stopping SSHD..."
    pkill -f /usr/sbin/sshd
    ;;
  restart)
    echo "Restarting SSHD..."
    pkill -f /usr/sbin/sshd
    /usr/sbin/sshd
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
