---
# tasks file for ssh-hardening

# once it runs on containers we need to
# manually create a sshd service file
- name: create ssh service
  copy:
    src: sshd
    dest: /etc/init.d/
    mode: 0554
  notify: restart sshd

- name: block user password login
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#PasswordAuthentication'
    line: 'PasswordAuthentication no'
  notify: restart sshd

- name: allow public key authentication login
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#PubkeyAuthentication'
    line: 'PubkeyAuthentication yes'
  notify: restart sshd
